In [2]:
import pandas as pd

In [69]:
df = pd.read_excel(r'C:\Users\lkiran\Desktop\python_contents\Parameter Comparison - India Food Park - IN-KA-RT-1003.xls',skiprows=1,index_col=0)

In [70]:
df

,A1509210239 - TotalEnergy,A1509210331 - TotalEnergy,A1509210338 - TotalEnergy,A1509210339 - TotalEnergy,A1509230543 - TotalEnergy,A1509230640 - TotalEnergy,A1509230678 - TotalEnergy,A1512040262 - TotalEnergy,A1512040280 - TotalEnergy,A1512040282 - TotalEnergy,A1512040289 - TotalEnergy,A1512040290 - TotalEnergy,A1512040306 - TotalEnergy,A1512040314 - TotalEnergy,A1512040316 - TotalEnergy,A1512040332 - TotalEnergy,A1512051145 - TotalEnergy,A1512051154 - TotalEnergy,INV - 01 - TotalEnergy
Time (In Hours),,,,,,,,,,,,,,,,,,,
2020-01-01 06:45:00,2692.0,64382.0,20787.0,14525.0,62452.0,21659.0,11710.0,61748.0,61947.0,61522.0,6782.0,60033.0,23808.0,23625.0,3409.0,25343.0,22616.0,22899.0,21418.0
2020-01-01 07:00:00,2692.0,64382.0,20787.0,14525.0,62452.0,21659.0,11710.0,61748.0,61947.0,61522.0,6782.0,60033.0,23808.0,23625.0,3409.0,25343.0,22616.0,22899.0,21418.0
2020-01-01 07:15:00,2692.0,64382.0,20787.0,14526.0,62453.0,21659.0,11710.0,61748.0,61947.0,61522.0,6782.0,60033.0,23809.0,23626.0,3409.0,25343.0,22617.0,22899.0,21418.0
2020-01-01 07:30:00,2693.0,64383.0,20788.0,14526.0,62453.0,21660.0,11710.0,61748.0,61947.0,61522.0,6782.0,60034.0,23809.0,23626.0,3409.0,25344.0,22617.0,22900.0,21419.0
2020-01-01 10:30:00,2715.0,64427.0,20820.0,14567.0,62473.0,21703.0,11741.0,61763.0,61965.0,61540.0,6811.0,60054.0,23844.0,23664.0,3422.0,25390.0,22657.0,22939.0,21463.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-01-31 17:30:00,5042.0,3271.0,24138.0,18714.0,64492.0,26171.0,14813.0,63253.0,63878.0,63395.0,9699.0,61994.0,27329.0,27532.0,4918.0,30353.0,26178.0,27046.0,25553.0
2020-01-31 17:45:00,5042.0,3272.0,24139.0,18715.0,64492.0,26172.0,14814.0,63253.0,63878.0,63395.0,9699.0,61994.0,27329.0,27532.0,4919.0,30354.0,26178.0,27046.0,25554.0
2020-01-31 18:00:00,5042.0,3272.0,24139.0,18715.0,64492.0,26172.0,14814.0,63253.0,63878.0,63395.0,9699.0,61994.0,27330.0,27532.0,4919.0,30354.0,26178.0,27047.0,25554.0
2020-01-31 18:30:00,5042.0,3272.0,24139.0,18715.0,64492.0,26172.0,14814.0,63253.0,63878.0,63395.0,9700.0,61994.0,27330.0,27532.0,4919.0,30355.0,26179.0,27047.0,25554.0
2020-01-31 18:45:00,5042.0,0.0,24139.0,NaN,64492.0,26172.0,NaN,63253.0,63878.0,63395.0,9700.0,61994.0,27330.0,27532.0,4919.0,30355.0,26179.0,27047.0,25554.0

In [29]:
df.std()

A1509210239 - TotalEnergy      842.188314
A1509210331 - TotalEnergy    24447.902107
A1509210338 - TotalEnergy     2430.239437
A1509210339 - TotalEnergy     2794.741267
A1509230543 - TotalEnergy     8292.911117
A1509230640 - TotalEnergy     2490.632690
A1509230678 - TotalEnergy     1765.382027
A1512040262 - TotalEnergy     7446.772447
A1512040280 - TotalEnergy     6836.352321
A1512040282 - TotalEnergy     5311.966153
A1512040289 - TotalEnergy      973.329677
A1512040290 - TotalEnergy     4261.051732
A1512040306 - TotalEnergy     1063.881433
A1512040314 - TotalEnergy     1730.523740
A1512040316 - TotalEnergy      543.105579
A1512040332 - TotalEnergy     3396.197867
A1512051145 - TotalEnergy     1603.889141
A1512051154 - TotalEnergy     1763.659669
INV - 01 - TotalEnergy        2861.958049
dtype: float64

In [37]:
df.isnull().sum()

Time (In Hours)               0
A1509210239 - TotalEnergy    56
A1509210331 - TotalEnergy    45
A1509210338 - TotalEnergy    39
A1509210339 - TotalEnergy    46
A1509230543 - TotalEnergy    56
A1509230640 - TotalEnergy    49
A1509230678 - TotalEnergy    50
A1512040262 - TotalEnergy    44
A1512040280 - TotalEnergy    40
A1512040282 - TotalEnergy    45
A1512040289 - TotalEnergy    42
A1512040290 - TotalEnergy    45
A1512040306 - TotalEnergy    40
A1512040314 - TotalEnergy    40
A1512040316 - TotalEnergy    45
A1512040332 - TotalEnergy    29
A1512051145 - TotalEnergy    41
A1512051154 - TotalEnergy    40
INV - 01 - TotalEnergy       35
dtype: int64

In [41]:
df["A1509210239 - TotalEnergy"]

0      2692.0
1      2692.0
2      2692.0
3      2693.0
4      2715.0
        ...
461    5042.0
462    5042.0
463    5042.0
464    5042.0
465    5042.0
Name: A1509210239 - TotalEnergy, Length: 466, dtype: float64

In [43]:
df["Two sum"] = df["A1509210239 - TotalEnergy"] + df["A1509210338 - TotalEnergy"]

In [44]:
df

,Time (In Hours),A1509210239 - TotalEnergy,A1509210331 - TotalEnergy,A1509210338 - TotalEnergy,A1509210339 - TotalEnergy,A1509230543 - TotalEnergy,A1509230640 - TotalEnergy,A1509230678 - TotalEnergy,A1512040262 - TotalEnergy,A1512040280 - TotalEnergy,...,A1512040289 - TotalEnergy,A1512040290 - TotalEnergy,A1512040306 - TotalEnergy,A1512040314 - TotalEnergy,A1512040316 - TotalEnergy,A1512040332 - TotalEnergy,A1512051145 - TotalEnergy,A1512051154 - TotalEnergy,INV - 01 - TotalEnergy,Two sum
0,2020-01-01 06:45:00,2692.0,64382.0,20787.0,14525.0,62452.0,21659.0,11710.0,61748.0,61947.0,...,6782.0,60033.0,23808.0,23625.0,3409.0,25343.0,22616.0,22899.0,21418.0,23479.0
1,2020-01-01 07:00:00,2692.0,64382.0,20787.0,14525.0,62452.0,21659.0,11710.0,61748.0,61947.0,...,6782.0,60033.0,23808.0,23625.0,3409.0,25343.0,22616.0,22899.0,21418.0,23479.0
2,2020-01-01 07:15:00,2692.0,64382.0,20787.0,14526.0,62453.0,21659.0,11710.0,61748.0,61947.0,...,6782.0,60033.0,23809.0,23626.0,3409.0,25343.0,22617.0,22899.0,21418.0,23479.0
3,2020-01-01 07:30:00,2693.0,64383.0,20788.0,14526.0,62453.0,21660.0,11710.0,61748.0,61947.0,...,6782.0,60034.0,23809.0,23626.0,3409.0,25344.0,22617.0,22900.0,21419.0,23481.0
4,2020-01-01 10:30:00,2715.0,64427.0,20820.0,14567.0,62473.0,21703.0,11741.0,61763.0,61965.0,...,6811.0,60054.0,23844.0,23664.0,3422.0,25390.0,22657.0,22939.0,21463.0,23535.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
461,2020-01-31 17:30:00,5042.0,3271.0,24138.0,18714.0,64492.0,26171.0,14813.0,63253.0,63878.0,...,9699.0,61994.0,27329.0,27532.0,4918.0,30353.0,26178.0,27046.0,25553.0,29180.0
462,2020-01-31 17:45:00,5042.0,3272.0,24139.0,18715.0,64492.0,26172.0,14814.0,63253.0,63878.0,...,9699.0,61994.0,27329.0,27532.0,4919.0,30354.0,26178.0,27046.0,25554.0,29181.0
463,2020-01-31 18:00:00,5042.0,3272.0,24139.0,18715.0,64492.0,26172.0,14814.0,63253.0,63878.0,...,9699.0,61994.0,27330.0,27532.0,4919.0,30354.0,26178.0,27047.0,25554.0,29181.0
464,2020-01-31 18:30:00,5042.0,3272.0,24139.0,18715.0,64492.0,26172.0,14814.0,63253.0,63878.0,...,9700.0,61994.0,27330.0,27532.0,4919.0,30355.0,26179.0,27047.0,25554.0,29181.0
465,2020-01-31 18:45:00,5042.0,0.0,24139.0,NaN,64492.0,26172.0,NaN,63253.0,63878.0,...,9700.0,61994.0,27330.0,27532.0,4919.0,30355.0,26179.0,27047.0,25554.0,29181.0

In [48]:
df.drop("Two sum",axis=1,inplace=True)

In [49]:
df

,Time (In Hours),A1509210239 - TotalEnergy,A1509210331 - TotalEnergy,A1509210338 - TotalEnergy,A1509210339 - TotalEnergy,A1509230543 - TotalEnergy,A1509230640 - TotalEnergy,A1509230678 - TotalEnergy,A1512040262 - TotalEnergy,A1512040280 - TotalEnergy,A1512040282 - TotalEnergy,A1512040289 - TotalEnergy,A1512040290 - TotalEnergy,A1512040306 - TotalEnergy,A1512040314 - TotalEnergy,A1512040316 - TotalEnergy,A1512040332 - TotalEnergy,A1512051145 - TotalEnergy,A1512051154 - TotalEnergy,INV - 01 - TotalEnergy
0,2020-01-01 06:45:00,2692.0,64382.0,20787.0,14525.0,62452.0,21659.0,11710.0,61748.0,61947.0,61522.0,6782.0,60033.0,23808.0,23625.0,3409.0,25343.0,22616.0,22899.0,21418.0
1,2020-01-01 07:00:00,2692.0,64382.0,20787.0,14525.0,62452.0,21659.0,11710.0,61748.0,61947.0,61522.0,6782.0,60033.0,23808.0,23625.0,3409.0,25343.0,22616.0,22899.0,21418.0
2,2020-01-01 07:15:00,2692.0,64382.0,20787.0,14526.0,62453.0,21659.0,11710.0,61748.0,61947.0,61522.0,6782.0,60033.0,23809.0,23626.0,3409.0,25343.0,22617.0,22899.0,21418.0
3,2020-01-01 07:30:00,2693.0,64383.0,20788.0,14526.0,62453.0,21660.0,11710.0,61748.0,61947.0,61522.0,6782.0,60034.0,23809.0,23626.0,3409.0,25344.0,22617.0,22900.0,21419.0
4,2020-01-01 10:30:00,2715.0,64427.0,20820.0,14567.0,62473.0,21703.0,11741.0,61763.0,61965.0,61540.0,6811.0,60054.0,23844.0,23664.0,3422.0,25390.0,22657.0,22939.0,21463.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
461,2020-01-31 17:30:00,5042.0,3271.0,24138.0,18714.0,64492.0,26171.0,14813.0,63253.0,63878.0,63395.0,9699.0,61994.0,27329.0,27532.0,4918.0,30353.0,26178.0,27046.0,25553.0
462,2020-01-31 17:45:00,5042.0,3272.0,24139.0,18715.0,64492.0,26172.0,14814.0,63253.0,63878.0,63395.0,9699.0,61994.0,27329.0,27532.0,4919.0,30354.0,26178.0,27046.0,25554.0
463,2020-01-31 18:00:00,5042.0,3272.0,24139.0,18715.0,64492.0,26172.0,14814.0,63253.0,63878.0,63395.0,9699.0,61994.0,27330.0,27532.0,4919.0,30354.0,26178.0,27047.0,25554.0
464,2020-01-31 18:30:00,5042.0,3272.0,24139.0,18715.0,64492.0,26172.0,14814.0,63253.0,63878.0,63395.0,9700.0,61994.0,27330.0,27532.0,4919.0,30355.0,26179.0,27047.0,25554.0
465,2020-01-31 18:45:00,5042.0,0.0,24139.0,NaN,64492.0,26172.0,NaN,63253.0,63878.0,63395.0,9700.0,61994.0,27330.0,27532.0,4919.0,30355.0,26179.0,27047.0,25554.0

In [53]:
df.loc['4']

KeyError: '4'

In [60]:
df.iloc[4]

Time (In Hours)              2020-01-01 10:30:00
A1509210239 - TotalEnergy                   2715
A1509210331 - TotalEnergy                  64427
A1509210338 - TotalEnergy                  20820
A1509210339 - TotalEnergy                  14567
A1509230543 - TotalEnergy                  62473
A1509230640 - TotalEnergy                  21703
A1509230678 - TotalEnergy                  11741
A1512040262 - TotalEnergy                  61763
A1512040280 - TotalEnergy                  61965
A1512040282 - TotalEnergy                  61540
A1512040289 - TotalEnergy                   6811
A1512040290 - TotalEnergy                  60054
A1512040306 - TotalEnergy                  23844
A1512040314 - TotalEnergy                  23664
A1512040316 - TotalEnergy                   3422
A1512040332 - TotalEnergy                  25390
A1512051145 - TotalEnergy                  22657
A1512051154 - TotalEnergy                  22939
INV - 01 - TotalEnergy                     21463
Name: 4, dtype: object

In [71]:
df

,A1509210239 - TotalEnergy,A1509210331 - TotalEnergy,A1509210338 - TotalEnergy,A1509210339 - TotalEnergy,A1509230543 - TotalEnergy,A1509230640 - TotalEnergy,A1509230678 - TotalEnergy,A1512040262 - TotalEnergy,A1512040280 - TotalEnergy,A1512040282 - TotalEnergy,A1512040289 - TotalEnergy,A1512040290 - TotalEnergy,A1512040306 - TotalEnergy,A1512040314 - TotalEnergy,A1512040316 - TotalEnergy,A1512040332 - TotalEnergy,A1512051145 - TotalEnergy,A1512051154 - TotalEnergy,INV - 01 - TotalEnergy
Time (In Hours),,,,,,,,,,,,,,,,,,,
2020-01-01 06:45:00,2692.0,64382.0,20787.0,14525.0,62452.0,21659.0,11710.0,61748.0,61947.0,61522.0,6782.0,60033.0,23808.0,23625.0,3409.0,25343.0,22616.0,22899.0,21418.0
2020-01-01 07:00:00,2692.0,64382.0,20787.0,14525.0,62452.0,21659.0,11710.0,61748.0,61947.0,61522.0,6782.0,60033.0,23808.0,23625.0,3409.0,25343.0,22616.0,22899.0,21418.0
2020-01-01 07:15:00,2692.0,64382.0,20787.0,14526.0,62453.0,21659.0,11710.0,61748.0,61947.0,61522.0,6782.0,60033.0,23809.0,23626.0,3409.0,25343.0,22617.0,22899.0,21418.0
2020-01-01 07:30:00,2693.0,64383.0,20788.0,14526.0,62453.0,21660.0,11710.0,61748.0,61947.0,61522.0,6782.0,60034.0,23809.0,23626.0,3409.0,25344.0,22617.0,22900.0,21419.0
2020-01-01 10:30:00,2715.0,64427.0,20820.0,14567.0,62473.0,21703.0,11741.0,61763.0,61965.0,61540.0,6811.0,60054.0,23844.0,23664.0,3422.0,25390.0,22657.0,22939.0,21463.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-01-31 17:30:00,5042.0,3271.0,24138.0,18714.0,64492.0,26171.0,14813.0,63253.0,63878.0,63395.0,9699.0,61994.0,27329.0,27532.0,4918.0,30353.0,26178.0,27046.0,25553.0
2020-01-31 17:45:00,5042.0,3272.0,24139.0,18715.0,64492.0,26172.0,14814.0,63253.0,63878.0,63395.0,9699.0,61994.0,27329.0,27532.0,4919.0,30354.0,26178.0,27046.0,25554.0
2020-01-31 18:00:00,5042.0,3272.0,24139.0,18715.0,64492.0,26172.0,14814.0,63253.0,63878.0,63395.0,9699.0,61994.0,27330.0,27532.0,4919.0,30354.0,26178.0,27047.0,25554.0
2020-01-31 18:30:00,5042.0,3272.0,24139.0,18715.0,64492.0,26172.0,14814.0,63253.0,63878.0,63395.0,9700.0,61994.0,27330.0,27532.0,4919.0,30355.0,26179.0,27047.0,25554.0
2020-01-31 18:45:00,5042.0,0.0,24139.0,NaN,64492.0,26172.0,NaN,63253.0,63878.0,63395.0,9700.0,61994.0,27330.0,27532.0,4919.0,30355.0,26179.0,27047.0,25554.0

In [75]:
df.loc['2020-01-01 07:00:00']

A1509210239 - TotalEnergy     2692.0
A1509210331 - TotalEnergy    64382.0
A1509210338 - TotalEnergy    20787.0
A1509210339 - TotalEnergy    14525.0
A1509230543 - TotalEnergy    62452.0
A1509230640 - TotalEnergy    21659.0
A1509230678 - TotalEnergy    11710.0
A1512040262 - TotalEnergy    61748.0
A1512040280 - TotalEnergy    61947.0
A1512040282 - TotalEnergy    61522.0
A1512040289 - TotalEnergy     6782.0
A1512040290 - TotalEnergy    60033.0
A1512040306 - TotalEnergy    23808.0
A1512040314 - TotalEnergy    23625.0
A1512040316 - TotalEnergy     3409.0
A1512040332 - TotalEnergy    25343.0
A1512051145 - TotalEnergy    22616.0
A1512051154 - TotalEnergy    22899.0
INV - 01 - TotalEnergy       21418.0
Name: 2020-01-01 07:00:00, dtype: float64

In [76]:
df.iloc[3]

A1509210239 - TotalEnergy     2693.0
A1509210331 - TotalEnergy    64383.0
A1509210338 - TotalEnergy    20788.0
A1509210339 - TotalEnergy    14526.0
A1509230543 - TotalEnergy    62453.0
A1509230640 - TotalEnergy    21660.0
A1509230678 - TotalEnergy    11710.0
A1512040262 - TotalEnergy    61748.0
A1512040280 - TotalEnergy    61947.0
A1512040282 - TotalEnergy    61522.0
A1512040289 - TotalEnergy     6782.0
A1512040290 - TotalEnergy    60034.0
A1512040306 - TotalEnergy    23809.0
A1512040314 - TotalEnergy    23626.0
A1512040316 - TotalEnergy     3409.0
A1512040332 - TotalEnergy    25344.0
A1512051145 - TotalEnergy    22617.0
A1512051154 - TotalEnergy    22900.0
INV - 01 - TotalEnergy       21419.0
Name: 2020-01-01 07:30:00, dtype: float64